### ISSUE TITLE
The opening question mark (¿) is wrongly flipped 

### ISSUE THREAD

**Issue by fitojb** [nguyentype/vinasans#1]
Opening question marks are not _mirrored_ versions of ? — they are _180 degree-rotated_ versions of ?. This means that ¿ should also hang below the baseline at the same level of lowercase letters with descenders, such as p, and its open end should face left.

**Comment by nguyentype** [comment]
> Opening question marks are not _mirrored_ versions of ? — they are _180 degree-rotated_ versions of ?. This means that ¿ should also hang below the baseline at the same level of lowercase letters with descenders, such as p, and its open end should face left.

Thank you for the feedback. The opening question mark is fixed! 🙏
